/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client.gui;

import client.pojos.R;
import common.pojos.Conventions;
import common.pojos.Message;
import common.pojos.OQueue;
import common.pojos.Utils;
import java.util.Observable;
import java.util.Observer;
import javax.swing.SwingUtilities;

/**
 *
 * @author johny
 */
public class SettingsPane extends javax.swing.JPanel implements Conventions, Observer {

    /**
     * Creates new form SettingsPane
     */
    public SettingsPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        mainPane = new javax.swing.JPanel();
        downloadsPane = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        networkPane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        versionPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jchatVersionLabel = new javax.swing.JLabel();
        checkVersionButton = new javax.swing.JButton();
        checkVersionLAL = new javax.swing.JLabel();
        checkVersionLAL.setVisible(false);
        checkVersionResponseLabel = new javax.swing.JLabel();
        checkVersionResponseLabel.setVisible(false);
        downloadNewVersionButton = new javax.swing.JButton();
        downloadNewVersionButton.setVisible(false);
        closeButtonBehaviorPane = new javax.swing.JPanel();
        saveSettingsButton = new javax.swing.JButton();
        settingsSavedLabel = new javax.swing.JLabel();
        settingsSavedLabel.setVisible(false);

        setName("SETTINGSPANE"); // NOI18N

        jLabel1.setBackground(new java.awt.Color(60, 59, 55));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 15)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Settings");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 25));

        mainPane.setBackground(java.awt.Color.white);
        mainPane.setPreferredSize(new java.awt.Dimension(250, 620));
        mainPane.setLayout(new javax.swing.BoxLayout(mainPane, javax.swing.BoxLayout.Y_AXIS));

        downloadsPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Download files", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Ubuntu", 2, 14), java.awt.Color.gray)); // NOI18N

        jTextField1.setText("/home/Downloads/");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Browse...");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("To:");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ask me every time");

        javax.swing.GroupLayout downloadsPaneLayout = new javax.swing.GroupLayout(downloadsPane);
        downloadsPane.setLayout(downloadsPaneLayout);
        downloadsPaneLayout.setHorizontalGroup(
            downloadsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, downloadsPaneLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(downloadsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addGroup(downloadsPaneLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(36, 36, 36))
        );
        downloadsPaneLayout.setVerticalGroup(
            downloadsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downloadsPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(downloadsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(20, 20, 20))
        );

        mainPane.add(downloadsPane);

        networkPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Network", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 2, 14), java.awt.Color.gray)); // NOI18N

        jLabel4.setText("Server IP Address:");

        jFormattedTextField1.setText(Conventions.SERVER_IP);
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout networkPaneLayout = new javax.swing.GroupLayout(networkPane);
        networkPane.setLayout(networkPaneLayout);
        networkPaneLayout.setHorizontalGroup(
            networkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkPaneLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        networkPaneLayout.setVerticalGroup(
            networkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkPaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(networkPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        mainPane.add(networkPane);

        versionPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "JChat Version", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 2, 14), java.awt.Color.gray)); // NOI18N

        jLabel2.setText("Current version: ");

        jchatVersionLabel.setText(R.JCHAT_VERSION);

        checkVersionButton.setText("Check for new version");
        checkVersionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVersionButtonActionPerformed(evt);
            }
        });

        checkVersionLAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/loading_circle_animation/21.gif"))); // NOI18N

        checkVersionResponseLabel.setForeground(new java.awt.Color(27, 210, 52));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("client/gui/Bundle"); // NOI18N
        checkVersionResponseLabel.setText(bundle.getString("checkVersionResponseLabel")); // NOI18N

        downloadNewVersionButton.setText(bundle.getString("downloadNewVersionButton")); // NOI18N
        downloadNewVersionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadNewVersionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout versionPaneLayout = new javax.swing.GroupLayout(versionPane);
        versionPane.setLayout(versionPaneLayout);
        versionPaneLayout.setHorizontalGroup(
            versionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(versionPaneLayout.createSequentialGroup()
                .addGroup(versionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(versionPaneLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(versionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(versionPaneLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jchatVersionLabel))
                            .addGroup(versionPaneLayout.createSequentialGroup()
                                .addComponent(checkVersionButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkVersionLAL))
                            .addComponent(checkVersionResponseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(versionPaneLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(downloadNewVersionButton)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        versionPaneLayout.setVerticalGroup(
            versionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(versionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(versionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jchatVersionLabel))
                .addGap(18, 18, 18)
                .addGroup(versionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkVersionButton)
                    .addComponent(checkVersionLAL))
                .addGap(18, 18, 18)
                .addComponent(checkVersionResponseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(downloadNewVersionButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        checkVersionLAL.getAccessibleContext().setAccessibleName("checkVersionLAL");

        mainPane.add(versionPane);

        saveSettingsButton.setText("Save Settings");
        saveSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSettingsButtonActionPerformed(evt);
            }
        });

        settingsSavedLabel.setForeground(new java.awt.Color(27, 210, 52));
        settingsSavedLabel.setText("Settings saved");

        javax.swing.GroupLayout closeButtonBehaviorPaneLayout = new javax.swing.GroupLayout(closeButtonBehaviorPane);
        closeButtonBehaviorPane.setLayout(closeButtonBehaviorPaneLayout);
        closeButtonBehaviorPaneLayout.setHorizontalGroup(
            closeButtonBehaviorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeButtonBehaviorPaneLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(closeButtonBehaviorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingsSavedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        closeButtonBehaviorPaneLayout.setVerticalGroup(
            closeButtonBehaviorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closeButtonBehaviorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveSettingsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingsSavedLabel)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        mainPane.add(closeButtonBehaviorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void checkVersionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVersionButtonActionPerformed
        checkVersionLAL.setVisible(true);
        R.send(new Message(NEWEST_VERSION_REQUEST));
    }//GEN-LAST:event_checkVersionButtonActionPerformed

    private void downloadNewVersionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadNewVersionButtonActionPerformed

        SoftwareUpdateFrame swuf = new SoftwareUpdateFrame();
        swuf.setVisible(true);

    }//GEN-LAST:event_downloadNewVersionButtonActionPerformed

    private void saveSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSettingsButtonActionPerformed
        //todo
        saveSettings();
        settingsSavedLabel.setVisible(true);
    }//GEN-LAST:event_saveSettingsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checkVersionButton;
    private javax.swing.JLabel checkVersionLAL;
    private javax.swing.JLabel checkVersionResponseLabel;
    private javax.swing.JPanel closeButtonBehaviorPane;
    private javax.swing.JButton downloadNewVersionButton;
    private javax.swing.JPanel downloadsPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jchatVersionLabel;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel networkPane;
    private javax.swing.JButton saveSettingsButton;
    private javax.swing.JLabel settingsSavedLabel;
    private javax.swing.JPanel versionPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (!arg.equals(this.getClass().getSimpleName())) {
            return;
        }

        OQueue q = ((OQueue) o);
        Message m = (Message) q.poll();

        switch (m.getCode()) {
            case NEWEST_VERSION_RESPONSE:
                final String newestVersion = (String) m.getContent();

                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        checkVersionLAL.setVisible(false);
                        if (Utils.isNewerVersion(newestVersion, R.JCHAT_VERSION)) {
                            checkVersionResponseLabel.setText("There is a new JChat version for you!");
                            downloadNewVersionButton.setText("Download JChat " + newestVersion);
                            downloadNewVersionButton.setVisible(true);
                        }
                        checkVersionResponseLabel.setVisible(true);
                    }
                });

        }
    }

    private void saveSettings() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
